//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization_History
    {
        public int ID_Auth { get; set; }
        public int ID_User { get; set; }
        public System.DateTime Time_Auth { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
