//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complete_tasks
    {
        public int ID_task { get; set; }
        public string Name_tasks { get; set; }
        public string Description_task { get; set; }
        public Nullable<System.DateTime> Date_start_job { get; set; }
        public Nullable<System.DateTime> Date_finish_job { get; set; }
    }
}
