//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date_Users
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<int> ID_role { get; set; }
        public virtual Role Role { get; set; }
        public virtual Users Users { get; set; }
    }
}
