//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Date_task()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int ID_task { get; set; }
        public string Name_task { get; set; }
        public string Description_task { get; set; }
        public Nullable<System.DateTime> Date_start_job { get; set; }
        public Nullable<System.DateTime> Date_finish_job { get; set; }
        public Nullable<int> ID_status { get; set; }
    
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
