//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID_Task_For_User { get; set; }
        public Nullable<int> ID_task { get; set; }
        public Nullable<int> ID_user { get; set; }
    
        public virtual Date_task Date_task { get; set; }
        public virtual Users Users { get; set; }
    }
}
